#!/usr/bin/env node
/**
 * Generate src/data/catalog.json — the authoritative plugin roster, derived
 * from the plugin build system (CMakeLists.txt) rather than hand-maintained.
 *
 *   node scripts/generate-catalog.mjs [path/to/CMakeLists.txt]
 *
 * This is the single source of truth for WHICH plugins exist. The website's
 * marketing data (src/data/plugins.ts) owns the copy/pricing/images, but its
 * roster must reconcile against this file — see scripts/check-catalog.mjs, which
 * runs in CI. Regenerate this whenever the plugin catalog changes.
 *
 * Runs LOCALLY only (it reads the sibling plugin repo, which isn't available in
 * CI). Commit the regenerated catalog.json; CI validates plugins.ts against it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const DEFAULT_CMAKE = join(ROOT, "..", "Plugin Development", "PrismAudioLabs", "CMakeLists.txt");
const OUT = join(ROOT, "src", "data", "catalog.json");

// Normalize a product name to a stable key for cross-referencing with the
// website roster. Accent-folds (Cajón -> cajon) so diacritics don't split a
// match. MUST match the norm() in scripts/check-catalog.mjs.
export const norm = (s) =>
  s.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .trim().toLowerCase().replace(/^prism[\s-]*/, "").replace(/[^a-z0-9]/g, "");

const cmakePath = process.argv[2] || DEFAULT_CMAKE;
let cmake;
try {
  cmake = readFileSync(cmakePath, "utf8");
} catch {
  console.error(`\n❌ Could not read CMakeLists.txt at:\n   ${cmakePath}\n`);
  console.error(`Pass the path explicitly: node scripts/generate-catalog.mjs <path>\n`);
  process.exit(1);
}

// Two CMake mechanisms define real build targets:
//   juce_add_plugin(... PRODUCT_NAME "Prism X" ...)
//   prism_plugin(<Target> "Prism X" ...)   <- macro for the effect pedals
const names = new Set();
for (const m of cmake.matchAll(/PRODUCT_NAME\s+"([^"]+)"/g)) names.add(m[1]);
for (const m of cmake.matchAll(/prism_plugin\([A-Za-z0-9_]+\s+"([^"]+)"/g)) names.add(m[1]);

const plugins = [...names]
  .filter((n) => !n.includes("${")) // drop CMake template artifacts like ${name}
  .sort()
  .map((name) => ({ name, key: norm(name) }));

// Guard against a normalization collision silently dropping a plugin.
const keys = new Set(plugins.map((p) => p.key));
if (keys.size !== plugins.length) {
  console.error("❌ Key collision after normalization — two plugins map to the same key. Fix norm().");
  process.exit(1);
}

const catalog = {
  _comment: "Generated by scripts/generate-catalog.mjs from the plugin build catalog. Do not edit by hand.",
  source: "Plugin Development/PrismAudioLabs/CMakeLists.txt",
  count: plugins.length,
  plugins,
};

writeFileSync(OUT, JSON.stringify(catalog, null, 2) + "\n");
console.log(`✅ Wrote ${plugins.length} plugins to src/data/catalog.json`);
